
GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoieW9ybWFuIiwiaWF0IjoxNjIxOTgzNTI1LCJleHAiOjE2MjE5ODM1NTV9.ReUVFxMSoBqm5akVNJfOkdc-1Mj5HFYMSnvA_AwT_bg



###

POST  http://localhost:3001/token
Content-Type: application/json

{
 "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoieW9ybWFuIiwiaWF0IjoxNjIxOTgzNTI1fQ.Kp7zar-j5zcBmw3t2OIMxoe6tCTcsijGb6xuM4MJTZ0"
}
###

POST  http://localhost:3001/login
Content-Type: application/json

{
 "username":"yorman"
}

###
DELETE http://localhost:3001/logout
Content-Type: application/json

{
 "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoia3lsZSIsImlhdCI6MTYyMTk4MTc1OCwiZXhwIjoxNjIxOTgxNzU4fQ.k3r67pr-WFM_RQynvS9YrKb7ddMhWjflyT1ZAY-F_vk"
}
